import { AdminStats, SessionRow } from "./api";

// Mock Guest Sessions - 5 examples with various statuses
export const MOCK_GUEST_SESSIONS: SessionRow[] = [
  {
    id: "mock-guest-001",
    guest_name: "John Smith",
    room_number: "401",
    is_verified: true,
    verification_score: 95,
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(), // 2 hours ago
    flow_type: "guest",
    liveness_score: 98,
    face_match_score: 92,
    status: "verified",
    extracted_info: {
      text: "PASSPORT - USA",
      textract: {
        full_name: "JOHN MICHAEL SMITH",
        nationality: "UNITED STATES",
        document_number: "C12345678",
        dob: "1985-03-15",
        raw: {
          id_type: "PASSPORT",
          first_name: "JOHN",
          middle_name: "MICHAEL",
          last_name: "SMITH",
          date_of_birth: "1985-03-15",
          date_of_issue: "2020-01-10",
          expiration_date: "2030-01-09",
          document_number: "C12345678",
          place_of_birth: "NEW YORK",
        },
      },
      textract_ok: true,
    },
    tm30_info: {
      nationality: "American",
      sex: "M",
      arrival_date_time: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      property: "RoomQuest Hotel",
      room_number: "401",
    },
    tm30_status: "ready",
  },
  {
    id: "mock-guest-002",
    guest_name: "Maria Garcia",
    room_number: "512",
    is_verified: true,
    verification_score: 88,
    created_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(), // 4 hours ago
    flow_type: "guest",
    liveness_score: 91,
    face_match_score: 85,
    status: "verified",
    extracted_info: {
      text: "PASSPORT - SPAIN",
      textract: {
        full_name: "MARIA ELENA GARCIA",
        nationality: "SPAIN",
        document_number: "PAA123456",
        dob: "1990-07-22",
        raw: {
          id_type: "PASSPORT",
          first_name: "MARIA",
          middle_name: "ELENA",
          last_name: "GARCIA",
          date_of_birth: "1990-07-22",
          date_of_issue: "2019-05-15",
          expiration_date: "2029-05-14",
          document_number: "PAA123456",
          place_of_birth: "MADRID",
        },
      },
      textract_ok: true,
    },
    tm30_info: {
      nationality: "Spanish",
      sex: "F",
      arrival_date_time: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
      property: "RoomQuest Hotel",
      room_number: "512",
    },
    tm30_status: "ready",
  },
  {
    id: "mock-guest-003",
    guest_name: "Wei Chen",
    room_number: "203",
    is_verified: false,
    verification_score: 45,
    created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(), // 1 hour ago
    flow_type: "guest",
    liveness_score: 52,
    face_match_score: 38,
    status: "failed",
    extracted_info: {
      text: "ID CARD - CHINA",
      textract: {
        full_name: "WEI CHEN",
        nationality: "CHINA",
        document_number: "310115199001011234",
        dob: "1990-01-01",
        raw: {
          id_type: "ID_CARD",
          first_name: "WEI",
          last_name: "CHEN",
          date_of_birth: "1990-01-01",
          document_number: "310115199001011234",
        },
      },
      textract_ok: true,
    },
    tm30_info: {
      nationality: "Chinese",
      sex: "M",
      property: "RoomQuest Hotel",
      room_number: "203",
    },
    tm30_status: "missing_fields",
  },
  {
    id: "mock-guest-004",
    guest_name: "Anna Mueller",
    room_number: "715",
    is_verified: false,
    verification_score: 0,
    created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(), // 30 mins ago
    flow_type: "guest",
    status: "pending",
    extracted_info: null,
    tm30_info: {},
    tm30_status: "pending",
  },
  {
    id: "mock-guest-005",
    guest_name: "James Wilson",
    room_number: "608",
    is_verified: true,
    verification_score: 92,
    created_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(), // 3 hours ago
    flow_type: "guest",
    liveness_score: 94,
    face_match_score: 90,
    status: "verified",
    expected_guest_count: 2,
    verified_guest_count: 2,
    guest_verifications: [
      {
        guest_index: 0,
        guest_verified: true,
        document_uploaded: true,
        selfie_uploaded: true,
        verification_score: 92,
        liveness_score: 94,
        face_match_score: 90,
        verified_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
      },
      {
        guest_index: 1,
        guest_verified: true,
        document_uploaded: true,
        selfie_uploaded: true,
        verification_score: 89,
        liveness_score: 91,
        face_match_score: 87,
        verified_at: new Date(Date.now() - 2.5 * 60 * 60 * 1000).toISOString(),
      },
    ],
    extracted_info: {
      text: "PASSPORT - UK",
      textract: {
        full_name: "JAMES WILSON",
        nationality: "UNITED KINGDOM",
        document_number: "533884729",
        dob: "1982-11-08",
        raw: {
          id_type: "PASSPORT",
          first_name: "JAMES",
          last_name: "WILSON",
          date_of_birth: "1982-11-08",
          date_of_issue: "2021-03-20",
          expiration_date: "2031-03-19",
          document_number: "533884729",
          place_of_birth: "LONDON",
        },
      },
      textract_ok: true,
    },
    tm30_info: {
      nationality: "British",
      sex: "M",
      arrival_date_time: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
      property: "RoomQuest Hotel",
      room_number: "608",
      notes: "Traveling with spouse - Sarah Wilson",
    },
    tm30_status: "ready",
  },
];

// Mock Visitor Sessions - 5 examples with access codes
export const MOCK_VISITOR_SESSIONS: SessionRow[] = [
  {
    id: "mock-visitor-001",
    guest_name: "David Brown",
    room_number: "",
    is_verified: true,
    verification_score: 100,
    created_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(), // 45 mins ago
    flow_type: "visitor",
    status: "approved",
    visitor_first_name: "David",
    visitor_last_name: "Brown",
    visitor_phone: "+66 81 234 5678",
    visitor_reason: "Package Delivery",
    visitor_access_code: "847291",
  },
  {
    id: "mock-visitor-002",
    guest_name: "Lisa Thompson",
    room_number: "",
    is_verified: true,
    verification_score: 100,
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(), // 2 hours ago
    flow_type: "visitor",
    status: "approved",
    visitor_first_name: "Lisa",
    visitor_last_name: "Thompson",
    visitor_phone: "+66 92 345 6789",
    visitor_reason: "Business Meeting",
    visitor_access_code: "293847",
  },
  {
    id: "mock-visitor-003",
    guest_name: "Michael Lee",
    room_number: "",
    is_verified: true,
    verification_score: 100,
    created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(), // 5 hours ago
    flow_type: "visitor",
    status: "approved",
    visitor_first_name: "Michael",
    visitor_last_name: "Lee",
    visitor_phone: "+66 83 456 7890",
    visitor_reason: "Maintenance",
    visitor_access_code: "582914",
  },
  {
    id: "mock-visitor-004",
    guest_name: "Emma Davis",
    room_number: "",
    is_verified: true,
    verification_score: 100,
    created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(), // 1 hour ago
    flow_type: "visitor",
    status: "approved",
    visitor_first_name: "Emma",
    visitor_last_name: "Davis",
    visitor_phone: "+66 84 567 8901",
    visitor_reason: "Property Viewing",
    visitor_access_code: "719382",
  },
  {
    id: "mock-visitor-005",
    guest_name: "Robert Kim",
    room_number: "",
    is_verified: true,
    verification_score: 100,
    created_at: new Date(Date.now() - 20 * 60 * 1000).toISOString(), // 20 mins ago
    flow_type: "visitor",
    status: "approved",
    visitor_first_name: "Robert",
    visitor_last_name: "Kim",
    visitor_phone: "+66 85 678 9012",
    visitor_reason: "Food Delivery",
    visitor_access_code: "461928",
  },
];

// Combined mock sessions
export const MOCK_SESSIONS: SessionRow[] = [
  ...MOCK_GUEST_SESSIONS,
  ...MOCK_VISITOR_SESSIONS,
];

// Mock admin stats matching the mock data
export const MOCK_ADMIN_STATS: AdminStats = {
  totalVerifications: 10,
  successfulVerifications: 8, // 4 verified guests + 5 visitors - 1 pending
  successRate: 80,
  totalCost: 2.50,
};
